FROM debian:stable

LABEL author="Michal Sedlak <xsedla0v@stud.fit.vutbr.cz>"

RUN apt-get update && apt-get install -y \
	build-essential \
	wget \
	git \
	cmake \
	docutils-common \
	autoconf \
	automake \
	pkg-config \
	libtool \
	libxml2-dev \
	liblz4-dev \
	libz-dev \
	libzstd-dev \
	librdkafka-dev \
	libssl-dev \
	libcurl4-openssl-dev

WORKDIR /root/

RUN git clone https://github.com/CESNET/libfds
RUN mkdir libfds-build \
	&& cd libfds-build \
	&& cmake ../libfds -DCMAKE_BUILD_TYPE=Debug \
	&& make \
	&& make install

RUN wget http://libnf.net/packages/libnf-1.25.tar.gz
RUN tar -xzf ./libnf-1.25.tar.gz \
	&& cd libnf-1.25 \
	&& ./configure \
	&& make \
	&& make install

RUN git clone https://github.com/CESNET/bloom-filter-index.git
RUN cd bloom-filter-index \
	&& ./bootstrap.sh \
	&& ./configure \
	&& make \
	&& make install

RUN git clone https://github.com/CESNET/Nemea-Framework
RUN cd Nemea-Framework \
	&& ./bootstrap.sh \
	&& ./configure \
	&& make \
	&& make install

RUN git clone https://github.com/aws/aws-sdk-cpp.git
RUN mkdir aws-sdk-cpp-build \
	&& cd aws-sdk-cpp-build \
	&& cmake ../aws-sdk-cpp -DCMAKE_BUILD_TYPE=Release -DBUILD_ONLY=s3 -DCUSTOM_MEMORY_MANAGEMENT=Off \
	&& make \
	&& make install

RUN git clone -b sedlak-s3 https://github.com/sedmicha/ipfixcol2
RUN mkdir ipfixcol2-build \
	&& cd ipfixcol2-build \
	&& cmake ../ipfixcol2 -DCMAKE_BUILD_TYPE=Debug \
	&& make \
	&& make install

RUN mkdir ipfixcol2-lnfstore-build \
	&& cd ipfixcol2-lnfstore-build \
	&& cmake ../ipfixcol2/extra_plugins/output/lnfstore -DCMAKE_BUILD_TYPE=Debug \
	&& make \
	&& make install

RUN mkdir ipfixcol2-unirec-build \
	&& cd ipfixcol2-unirec-build \
	&& cmake ../ipfixcol2/extra_plugins/output/unirec -DCMAKE_BUILD_TYPE=Debug \
	&& make \
	&& make install

RUN mkdir ipfixcol2-ipfix-s3-input-build \
	&& cd ipfixcol2-ipfix-s3-input-build \
	&& cmake ../ipfixcol2/extra_plugins/input/ipfix-s3 -DCMAKE_BUILD_TYPE=Debug \ 
	&& make \
	&& make install

RUN mkdir ipfixcol2-ipfix-s3-output-build \
	&& cd ipfixcol2-ipfix-s3-output-build \
	&& cmake ../ipfixcol2/extra_plugins/output/ipfix-s3 -DCMAKE_BUILD_TYPE=Debug \ 
	&& make \
	&& make install

COPY startup.xml /usr/local/etc/ipfixcol2/
EXPOSE 4739/udp
ENV LD_LIBRARY_PATH=/usr/local/lib/
ENTRYPOINT ["/usr/local/bin/ipfixcol2"]
